runtime: python           #linguagem
env: flex                 #ambiente
#entrypoint: gunicorn -b :$PORT main:app     #start

#env_varibles:
#  BASIC_AUTH_USERNAME: julio
#  BASIC_AUTH_PASSWORD: alura

runtime_config:
  python_version: 3

includes: 
  - env_vars.yaml